// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/253e456e3c0bf4bd34afaceb7dcbae282da14066/pg-types/index.d.ts
declare module "pg-types" {

    interface TypeParser {
        (value: any): any;
    }

    export function getTypeParser(oid: number, format: string): TypeParser;

    export function setTypeParser(oid: number, format: string, parseFn: TypeParser): void;
    export function setTypeParser(oid: number, parseFn: TypeParser): void;

    export namespace arrayParser {

        export function create(source: any, transform: TypeParser): { parse: () => any[] };

    }

}
